---
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create